services:
  sechat.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
      - ASPNETCORE_HTTPS_PORTS=3001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/sechat.pfx


    container_name: sechat.server
    image: sechat.server
    build:
      context: seChat.Server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ~/.aspnet/https:/https:ro
  sechat.client:
    build:
      context: sechat.client
      dockerfile: Dockerfile
    image: sechat.client
    container_name: sechat.client
    ports:
      - "5000:5000"
    depends_on:
      - sechat.server

